#!/bin/bash

set -e

_other_installs () {
    if [[ -n "$OTHER_INSTALLS" && "$OTHER_INSTALLS" != "None" ]]
    then
        apt install $OTHER_INSTALLS -y
    fi
}

_externals () {
    if [[ -n "$OTHER_CMD" && "$OTHER_CMD" != "None" ]]
    then
        eval "$OTHER_CMD"
    fi
}

echo "================================="
echo "       DLK DEVELOPER SETUP"
echo "================================="

apt update -y
apt upgrade -y

_other_installs

python3 -m pip install --upgrade pip

if [ -f "requirements.txt" ]
then
    python3 -m pip install -U -r requirements.txt
else
    echo "ERROR: requirements.txt not found!"
    exit 1
fi

_externals

echo "================================="
echo "       STARTING DLK BOT"
echo "================================="

python3 -m SPAMBOT